Разметка
htmlacademy-adaptive/122895-mishka-27 pull request #2
Opened 2022-12-06 20:01 UTC by knosal

1. Не всегда ясно как миксовать. Вот вроде в разделе с отзывом, он вроде как не используется больше нигде, как и контролы (стрелки), но в тоже время все делать элементом самих отзывов как то странно, нет?
2. Вопрос по иконкам, до этого вставлял через svg т.к. они меняют цвет при наведении, как лучше делать? вставлять как модификатор и css или через svg?

---
:mortar_board: [Разметка](https://up.htmlacademy.ru/adaptive/27/user/122895/tasks/4)

:boom: https://htmlacademy-adaptive.github.io/122895-mishka-27/2/

2022-12-09 09:50 UTC, pavel-nyukalo requested changes
1. Насчет именования файлов - у нас должно быть единообразие.

![image](https://user-images.githubusercontent.com/52506235/206666708-148d65e8-ea5a-4219-bd71-4d626ec5c2dd.png)

То есть если используем дефис, то он используется везде в разделении слов -> `advantages-flower-icon.svg`

2. > 1. Не всегда ясно как миксовать. Вот вроде в разделе с отзывом, он вроде как не используется больше нигде, как и контролы (стрелки), но в тоже время все делать элементом самих отзывов как то странно, нет?

Помни, что для каждого БЭМ-блока у нас будет свой файл стилей. И если делать не элементами, а например блоками, то придется много файлов создавать, где будет по пару свойств. Не очень оптимально

3. > Вопрос по иконкам, до этого вставлял через svg т.к. они меняют цвет при наведении, как лучше делать? вставлять как модификатор и css или через svg?

Если иконка меняет цвет, то ее в разметку через <svg>. Если это декоративная фоновая картинка, то модификаторами

2022-12-09 09:50 UTC, pavel-nyukalo commented on package.json
> +    "editorconfig": "editorconfig",
Как уже описал - это ломает скрипт проверки, нужно вернуть как было.

Основная ошибка - у тебя использованы табы вместо пробелов, и это не пройдет соответственно проверку при сдаче проекта. Надо заменить табы на пробелы

2022-12-09 09:50 UTC, pavel-nyukalo commented on source/img/svg/logo.svg
> +<svg width="149" height="72" viewBox="0 0 149 72" fill="none" xmlns="http://www.w3.org/2000/svg">
Здесь неполностью картинка экспортировалась

![image](https://user-images.githubusercontent.com/52506235/206666999-95614d8e-3263-4359-9ee8-fdfb659ea1d4.png)

2022-12-09 09:50 UTC, pavel-nyukalo commented on source/index.html
> +					<svg
Логотип у нас при взаимодействии получает только `opacity`, поэтому вставлять его через `svg` нет смысла. Поэтому лучше на `img` заменить, чтобы а) потом его адаптировать под разные разрешение и б) не было такой портянки из `path` и тд

2022-12-09 09:50 UTC, pavel-nyukalo commented on source/index.html
> +						</table>
Предложил бы реализовать через [`dl dd dt`](https://doka.guide/html/dl-dd-dt/), как раз пары ключ-значение

2022-12-09 09:50 UTC, pavel-nyukalo commented on source/index.html
> +					<button class="featured__button button-primary">Заказать</button>
Не забываем указывать `type` у кнопок

2022-12-09 09:50 UTC, pavel-nyukalo commented on source/index.html
> +					</button>
Это по [ТЗ](https://up.htmlacademy.ru/adaptive/27/project/mishka#mishka-4-5) ссылкой должно быть

2022-12-09 09:50 UTC, pavel-nyukalo commented on source/index.html
> +						</p>
По стайлгайду выглядит ссылкой

![image](https://user-images.githubusercontent.com/52506235/206672314-42a5d834-9414-4fc1-9a68-1a4a8304b928.png)

2022-12-09 09:50 UTC, pavel-nyukalo commented on source/index.html
> +					</button>
Аналогично [ссылкой](https://up.htmlacademy.ru/adaptive/27/project/mishka#mishka-4-7)

2022-12-09 09:50 UTC, pavel-nyukalo commented on source/index.html
> +				</button>
Здесь нужно будет сделать форму и радио-кнопочки

2022-12-09 09:50 UTC, pavel-nyukalo commented on source/catalog.html
> +					<svg
Аналогично, как в индексе

2022-12-09 09:50 UTC, pavel-nyukalo commented on source/catalog.html
> +							<h3 class="product__title">Зайчик-попрыгайчик</h3>
Тут тоже по [ТЗ](https://up.htmlacademy.ru/adaptive/27/project/mishka#mishka-6-1) ссылки

2022-12-09 09:50 UTC, pavel-nyukalo commented on source/catalog.html
> +						</svg>
Я бы заменил на `img`, опять же при нажатии добавляется только `opacity`. Плюс обернуть бы в кнопку, мы же можем нажать

2022-12-09 09:50 UTC, pavel-nyukalo commented on source/catalog.html
> +					<div class="production__info-inner production__info-inner--icon">
Плюс по [ТЗ](https://up.htmlacademy.ru/adaptive/27/project/mishka#mishka-6-3) нам надо сюда картинку добавить

2022-12-09 09:50 UTC, pavel-nyukalo commented on source/form.html
> +										class="visually-hidden input-text"
Точно ли нужен `visually-hidden`? Поле у нас видимо и необходимо для заполнения

2022-12-09 09:50 UTC, pavel-nyukalo commented on source/form.html
> +						<button class="form__button button-primary">Отправить заказ</button>
`type` стоит проверить у всех кнопок

2022-12-13 09:31 UTC, knosal commented on source/index.html
> +						</table>
Вообще сейчас используют таблицы? или их максимально избегают?

2022-12-13 10:55 UTC, knosal commented on source/catalog.html
> +					<div class="production__info-inner production__info-inner--icon">
Перенес модификатор для иконки на заголовок, она скорее там нежели на блоке, не нашел в стайлгайде как она меняется, но думаю максимум прозрачность.

2022-12-14 11:23 UTC, pavel-niukalo commented on source/img/svg/assortment__interior-icon.svg
> +<svg width="40" height="62" viewBox="0 0 40 62" fill="none" xmlns="http://www.w3.org/2000/svg">
В названиях все еще присутствует разнообразие (__ и -)

![image](https://user-images.githubusercontent.com/52506235/207581514-30243a0a-7a32-407e-a235-0c76ef9f8105.png)

У гитхаба есть такой баг - если поменять просто название файла, то оно не поменяется.

Тут нам надо удалить картинки -> запушить, чтобы они и из форка удалились -> снова добавить картинки, но уже с корректными названиями -> снова запушить. В таком случае названия поменяются на корректные

2022-12-14 11:23 UTC, pavel-niukalo commented on source/index.html
> +              </div>
Нужен ли нам этот div? Вполне могут завернуть критерий про лишние элементы. Мы можем сразу ссылку стилизовать и оставить только

```html
<a class="assortment__link " href="#">
  Предметы интерьера
</a>
```

2022-12-14 11:23 UTC, pavel-niukalo commented on source/index.html
> +						</table>
Для табличных данных используют. Тут у нас пары ключ-значение, поэтому семантичнее подойдет именно dl dd dt

2022-12-14 11:30 UTC, pavel-nyukalo requested changes

2022-12-14 11:30 UTC, pavel-nyukalo commented on source/index.html
> +            <ul class="form__list form__list-current">
`form__list-current` похож на модификатор, тогда надо сделать `form__list--current`

2022-12-14 11:30 UTC, pavel-nyukalo commented on source/catalog.html
> +            <ul class="form__list form__list-current">
+1 к `current`

2022-12-14 11:30 UTC, pavel-nyukalo commented on source/form.html
> +                <input class="visually-hidden input-text" type="text" placeholder="Введите ваше имя*" required>
`visually-hidden` на этих инпутах не нужен. `visually-hidden` прячет элемент, а эти инпуты у нас видны и присутствуют в разметке

![image](https://user-images.githubusercontent.com/52506235/207583861-c6fc4b4b-5b5f-4392-89b6-cfc679313374.png)

2022-12-15 11:19 UTC, pavel-nyukalo requested changes

2022-12-15 11:19 UTC, pavel-nyukalo commented on source/index.html
> +        <img class="main-header__logo-icon" src="/source/img/svg/main-header__logo-mobile-icon.svg" width="86" height="35" alt="Логотип сайта 'Мишка'">
1. Пути надо писать от файла `html`. Потом у нас на сервере и в папке `dist` папки `source` не будет. Так что такие пути не заработают. Нужно просто `src="img/....."`

2. Про именование файлов. Я имею ввиду, что у нас слова в названии файла должны разделяться единообразно. Не называй файлы по БЭМ-блоку, эти картинки в целом могут и в другом месте использоваться. И используем дефис в разделении

Например, `main-header__logo-mobile-icon.svg` должен стать `main-header-logo-mobile-icon.svg`, но опять же абстрагируемся от БЭМ -> `logo-mobile-icon.svg` и тд

2022-12-15 11:19 UTC, pavel-nyukalo commented on source/form.html
> +              </label>
Смотри, на этом (и других видимых) инпуте все еще висит `visually-hidden`

`visually-hidden` у нас скрывает элемент. То есть мы просто не увидим вот этот инпут в конечном итоге

![image](https://user-images.githubusercontent.com/52506235/207845862-fe111245-d611-48bb-ade0-b7d70536e569.png)

А он нам нужен, у него вон плейсхолдер есть, да и в целом, чтобы что-то ввести можно было

`visually-hidden` навешивается на инпут в том случае, когда нам надо спрятать его чтобы застилизовать как нужно. Например, чекбоксы и радио кнопки. Они в старых браузерах плохо поддаются стилизации, и поэтому для них вводится доп. тег, который мы и стилизуем

Например, вот 
```html
<input class="visually-hidden item-control__radio input-radio" type="checkbox">
<span class="item-control__icon"></span>
Черный
```

Стилизовать будем `item-control__icon`, при это инпут скрыт

2022-12-15 11:36 UTC, knosal commented on source/form.html
> +              </label>
Да, я понял)) не везде удалил visually-hidden

2022-12-15 12:12 UTC, pavel-nyukalo approved these changes

2022-12-15 12:13 UTC, merged