4.15. Адаптивная сетка (планшет)
htmlacademy-adaptive/122895-mishka-27 pull request #4
Opened 2022-12-29 19:56 UTC by knosal

Вопросы:
**

- [ ] 1.	@media должны быть отдельно после каждого селектора? или можно как-то объединять?
- [ ] 2.	Верно ли задумана шапка?

**
  Т.е. я беру сначала обертку и задаю ей раскладку grid, указываю области, но т.к. часть именованных обастей находится в общем блоке, то по раскладке оно не строиться, я уже в этом, общем блоке, строю аналогично раскладку и указываю уже там нужные области. Но кажется как-то сложно и костыльно.  Да и логотип в данном случае под слоем находится. Аналогичным способом делал раздел с отзывами. Имеет ли место быть данный подход?

![image](https://user-images.githubusercontent.com/35274816/210004383-e583f55a-75ef-453f-8557-ba19015bedc3.png)

![image](https://user-images.githubusercontent.com/35274816/210004398-e3cd33c0-9a29-41eb-bde8-136c42d06a56.png)

 Также косательно шапки не очень ясно как сместить общий контент вверх, чтобы часть фона была серой, отрицательным отступом как-то не вышло, пока еще думаю над этим. 
**

- [ ] 3.	Нужно ли явно прописывать grid-area?

**

К примеру раздел featured (вторая секция - Вязаные корзинки), grid-area указывал явно только title, остальное автоматом указано, нужно ли явно прописывать в каждом блоке?

![image](https://user-images.githubusercontent.com/35274816/210004525-60bcea44-ec68-400a-a64e-8fe57deaaa00.png)

**

- [ ] 4.	Как более правильно поменять порядок в списке "Коротко о нас", там на мобилке и планшете разный порядок?

** 

Думал либо отдельный контейнер каждому из блоков сделать, но мне кажется не самый лучший вариант. Либо через order поменять порядок.
 
![image](https://user-images.githubusercontent.com/35274816/210004566-c2cd96a0-7606-46c9-9657-dfe52cb7a63e.png)

![image](https://user-images.githubusercontent.com/35274816/210004562-5f600f09-39cf-4295-9f7f-ce415b6a8293.png)

**

- [ ] 5.	Как будет более верно с точки зрения разметки?

**

![image](https://user-images.githubusercontent.com/35274816/210004662-106a49c9-20dd-48b0-85e6-72b2b181a6ae.png)

Думал внести стрелки в общий блок с самим отзывов, так проще всего для реализации на гридах, но не логично т.к. элемент повторяется. Или же вынести отдельно и абсолютно с позиционировать, т.к. иначе не получается внести в одну линию с автором.

**

- [ ] 6.	Как правильно оформить filedset?

** 
Читал про группировку и проблемно использовать grid или flex, либо внутренность обернуть в блок надо, но на это ругается валидатор, либо заменить filedset на div.

**

- [ ] 7.	Не понимаю как убрать gap между телефоном и майлом?

**

ну т.е. хотелось универсально задать отступ для всех блоков, т.к. он одинаковый, загвоздка только в этих разделах, можно отдельно для каждого конечно сделать. 

![image](https://user-images.githubusercontent.com/35274816/210005043-450dc181-2495-4b1f-8425-6bfe36bfbaae.png)

Думал объединить их в блок, но они как то не как задумано выстраиваются.

![image](https://user-images.githubusercontent.com/35274816/210005142-013d9cb1-2a77-4ea2-a7df-1a43f9e538b0.png)

Очень проблемные филдсеты, отказаться уже готов, решил сначала попробовать справиться так с ними.

2022-12-30 15:52 UTC, pavel-nyukalo requested changes
Не забывай, что все что упирается в края макета должно растягиваться на _всю_ ширину окна, а не только на брейкпоинтах

![image](https://user-images.githubusercontent.com/52506235/210083790-64df20f4-a4d0-4d60-a525-485e140e3825.png)

![image](https://user-images.githubusercontent.com/52506235/210083850-781189b6-99d3-4a4f-8435-4c62726fe61e.png)

![image](https://user-images.githubusercontent.com/52506235/210083880-dc89bdfa-1d8e-44f7-a81c-70713592af38.png)

Отвечаю на вопросы:

1. В комментарии к коду надеюсь ответил, но коротко повторю - можно объединить да, прописать один раз запрос и там описать все остальное

2. То что логотип находится за слоем это плохо да, поскольку на него нет возможности нажать теперь. Скорее всего тут будет проще реализовать через абсолютное позиционирование (шапка очень мудренная и сложная), плюс надо держать в голове тест на переполнение. Можно будет поиграться с `calc` и процентами

3. Да, при использовании именованных областей нужно явно указывать каждому элементу какую область ему занять

4. Я думаю тут `order` хорошо подойдет. Обертки будут лишними

5.  С точки зрения разметки эти кнопки у нас должны быть прописаны ровно один раз. Это и по логике (поскольку они относятся ко всему слайдеру, а не к каждому слайду) и при навешивании интерактивности с JS будет проще. А стилизовать уже можно и абсолютным позиционированием, да

6 и 7. Если с фиелдсетами проблемы, можно их заменить на `div` и заголовки

Можешь еще вот [здесь](https://discord.com/channels/886917685244473394/1055220577348100196/1056463242530136084) почитать, тоже обсуждали замену фиелдсетов

Но опять же, отвечая на 7 вопрос. У тебя отступ задан у `grid`-контейнера

![image](https://user-images.githubusercontent.com/52506235/210088454-cef5389e-98fa-4cde-b643-a2d02dacdfb1.png)

Плюс используется `display: contents` и в нем легко запутаться. Поэтому как вариант, я бы предложил не гридами на общей форме строить сетку, а просто потоком. То бишь каждому фиелдсету сетку строить внутри этого фиелдсета

2022-12-30 15:52 UTC, pavel-niukalo commented on source/catalog.html
> +          <ul class="main-navigation__list navigation-list navigation-list__site">
Не видел где-то запрета, но чисто логически получается, что блок является и элементом самого себя же (`navigation-list navigation-list__site`). Думаю, `navigation-list__site` лишнее. Или это модификатор?

2022-12-30 15:52 UTC, pavel-niukalo commented on source/catalog.html
> +          <ul class="main-navigation__list navigation-list navigation-list__promotions visually-hidden">
Вот тут тоже `navigation-list__promotions`, скорее всего это больше модификаторы

2022-12-30 15:52 UTC, pavel-nyukalo commented on source/index.html
> +        </div>
`reviews__control` у нас на странице должны быть один раз прописаны, без дублирования

Меняется только текст отзывов, кнопки же одни на весь слайдер

2022-12-30 15:52 UTC, pavel-nyukalo commented on source/sass/components/advantages.scss
> +}
Я бы предложил тебе выбрать один из двух способов:

1. Пишем медиа-запрос прямо в селекторе (примерно как сейчас у тебя, но ты получается лишний раз дублируешь селектор

То есть вместо

```scss
.advantages__list {
  @include bootstrap.ul-reset;
  display: flex;
  flex-direction: column;
  gap: 25px;
}

@media (min-width: bootstrap.$tablet-width) {
  .advantages__list {
    display: grid;
    grid-template-columns: 1fr 1fr;
    column-gap: 100px;
    row-gap: 57px;
  }
}
```

Будет
```scss
.advantages__list {
  @include bootstrap.ul-reset;
  display: flex;
  flex-direction: column;
  gap: 25px;
  
  @media (min-width: bootstrap.$tablet-width) {
    display: grid;
    grid-template-columns: 1fr 1fr;
    column-gap: 100px;
    row-gap: 57px;
  }
}
```

2. Прописываем медиа запрос один раз и в нем все описываем

```scss
.class-1 {
  ...
}

.class-2 {
  ...
}

@media (min-width: bootstrap.$tablet-width) {
  .class-1 {
    ...
  }
  
  .class-2 {
    ...
  }
}
```

2022-12-30 15:52 UTC, pavel-nyukalo commented on source/sass/components/navigation-list.scss
> +  &__promotions {
Для элементов `&` запрещен, поэтому еще один повод сделать модификаторами

2023-01-11 10:21 UTC, pavel-nyukalo requested changes
Адаптивность выглядит хорошо, но я бы предложил на десктопе ее ограничивать по ширине.

Предположим пользователь открыл сайт на 4к мониторе

И у него сайт будет отображаться так

![image](https://user-images.githubusercontent.com/52506235/211781250-0ae4a26b-3ee2-4923-8565-4cce3a4261ed.png)

![image](https://user-images.githubusercontent.com/52506235/211781269-0bca39e8-ff63-4520-b530-1918e5ed1d65.png)

То есть очень большие промежутки между элементами, поэтому мне кажется лучше отцентрировать на десктопе и не тянуть дальше.

Так же, про вот эти полоски. На мобилке и планшете они тянутся да, все верно. Но на декстопе по макету они уже не тянутся

![image](https://user-images.githubusercontent.com/52506235/211781424-e8fa5f9d-3584-4df1-aaca-038fd3760079.png)

2023-01-11 10:21 UTC, pavel-niukalo commented on source/catalog.html
> +        <h1 class="catalog__title __title">Каталог товаров</h1>
`__title` - тут не по БЭМ написано, это вырванный элемент получается

2023-01-11 10:21 UTC, pavel-niukalo commented on source/form.html
> +      <div class="order__text">
Думаю стоит оставить это именно параграфом - `<p>`.

2023-01-11 10:21 UTC, pavel-niukalo commented on source/form.html
> +            <p class="form__legend form__legend--radio form__legend--line">Тип</p>
А это можно заголовком

2023-01-11 10:21 UTC, pavel-nyukalo commented on source/catalog.html
> +          <div class="main-header__delivery-promo">Бесплатная доставка по России</div>
Тут тоже думаю больше текстовый тег подходит, `<p>` или `<span>`

2023-01-11 10:21 UTC, pavel-nyukalo commented on source/sass/components/reviews.scss
> +}
Лучше придерживаться единообразия, сейчас в проекте мы используем медиа внутри селекторов

![image](https://user-images.githubusercontent.com/52506235/211780994-a6f7a710-4b2d-407b-a474-d8592885a9ad.png)

Эти так же нужно переделать на внутренние медиа

2023-01-12 06:10 UTC, knosal commented on source/catalog.html
> +        <h1 class="catalog__title __title">Каталог товаров</h1>
Это ошибка, что-то не до удалил

2023-01-13 09:57 UTC, pavel-nyukalo requested changes
Снова приходим к тому, что все что упирается - должно тянуться. Можно добавить доп. обертки, которые будут центрировать контент (то что в предыдущий раз писал), но тянуть все равно нужно упирающиеся фоны и тд

![image](https://user-images.githubusercontent.com/52506235/212291597-afce0553-7308-4ccf-839c-a88a2f5d89cc.png)

2023-01-13 09:57 UTC, pavel-nyukalo commented on source/sass/components/item-control.scss
> +  &:active .control__icon {
`control__icon` - элемент блока `control`. Соответственно в этом файле его быть не долдно

2023-01-13 10:15 UTC, knosal commented on source/sass/components/item-control.scss
> +  &:active .control__icon {
Ошибка, не увидел, надо удалить.

2023-01-15 16:57 UTC, pavel-nyukalo requested changes

2023-01-15 16:57 UTC, pavel-nyukalo commented on source/sass/components/main-navigation.scss
> +    &--closed .navigation-list__item {
`.navigation-list__item` тут не должно быть, поскольку этот файл у нас для `main-navigation`

Как вариант - завязаться на класс `main-navigation__list`. И менять `display` у него

2023-01-15 17:03 UTC, knosal commented on source/sass/components/main-navigation.scss
> +    &--closed .navigation-list__item {
Да, это был проблемный вопрос

2023-01-15 20:07 UTC, knosal commented on source/sass/components/main-navigation.scss
> +    &--closed .navigation-list__item {
Не понятно зачем вообще я начал ссылаться на элементы, а не на весь список.

2023-01-16 10:45 UTC, pavel-nyukalo approved these changes

2023-01-16 10:45 UTC, merged