8.14. Автоматизация сборки личного проекта
htmlacademy-adaptive/122895-mishka-27 pull request #9
Opened 2023-01-20 19:18 UTC by knosal

2023-01-22 17:26 UTC, pavel-nyukalo requested changes
В опубликованной версии пропали картинки

![image](https://user-images.githubusercontent.com/52506235/213927858-179fd055-1f00-47fb-9964-6231dc71a3bb.png)

![image](https://user-images.githubusercontent.com/52506235/213927882-28b2dcbe-c051-4590-b52e-cfc79bb8da28.png)

![image](https://user-images.githubusercontent.com/52506235/213927894-fc9b8bdc-96e6-41ca-9e0d-dfdd5c474d5a.png)

2023-01-22 17:26 UTC, pavel-niukalo commented on source/catalog.html
> +          <svg class="production__video-play-icon" width="101" height="77" viewBox="0 0 101 77" fill="none" xmlns="http://www.w3.org/2000/svg" aria-label="Воспроизвести видео" tabindex="0">
Я думаю тут можно еще иконку эту в кнопку обернуть и тогда не надо будет `tabindex`

2023-01-22 17:26 UTC, pavel-niukalo commented on source/catalog.html
> +  @@include("header.html",{})
Аа, вот что ты имел ввиду под `include`

Хм, ну запрета в критериях я не видел, но не знаю, напишет ли проверяющий что-то про это

2023-01-22 17:26 UTC, pavel-niukalo commented on source/index.html
> +            <span class="visually-hidden">Следующий отзыв</span>
Как раз про это написал в дискорде - если есть одно, второе не нужно. Чтобы скринридер не читал два раза одно и тоже

2023-01-22 18:45 UTC, knosal commented
Честно говоря, не очень понимаю почему?!

2023-01-22 18:46 UTC, knosal commented
При сборке все ок, а когда заливаю на гитхаб что-то не так

2023-01-24 07:34 UTC, pavel-nyukalo approved these changes

2023-01-24 07:34 UTC, merged